import Main from "@/components/Main";
import { Heading } from "@chakra-ui/layout";
import Head from "next/head";

export default function Index() {
  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Hello world</Heading>
    </Main>
  );
}
