import Main from "@/components/Main";
import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Heading, Stack, Text, VStack } from "@chakra-ui/layout";
import Head from "next/head";
import Image from "next/image";
export default function Index() {
  const bgColor = useColorModeValue("none", "whiteAlpha.50");
  const invertColor = useColorModeValue("none", "invert(10%) brightness(120%)");
  return (
    <Main justifyContent={["start", "center"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        direction={["column-reverse", "row"]}
        justifyContent="space-between"
      >
        <VStack alignItems={["center", "start"]} justifyContent="center">
          <Heading>Hi, I'm Wisesa. 🐱</Heading>
          <Text textAlign={["center", "left"]} maxW="550px">
            A student and a software <i>edgy</i>neer. I love exploring new
            technology and now fall in love with react.js and javascript.
          </Text>
        </VStack>
        <Box filter={invertColor}>
          <Image src="/me.svg" width="400px" height="400px" />
        </Box>
      </Stack>
    </Main>
  );
}
